* util/texi2dvi (insert_commands): Use fatal for errors. (insert_commands): Actually, use "error", not "fatal". White space changes.

diff --git a/util/texi2dvi b/util/texi2dvi
--- a/util/texi2dvi
+++ b/util/texi2dvi
@@ -1078,7 +1078,7 @@ insert_commands ()
   case $in_lang in
     latex)   textra_cmd=1i;;
     texinfo) textra_cmd='/^@setfilename/a';;
-    *)       fatal 1 "internal error, unknown language: $in_lang";;
+    *)       error 1 "internal error, unknown language: $in_lang";;
   esac
 
   if test -n "$textra"; then
@@ -1268,6 +1268,7 @@ remove ()
   verbose "Removing" "$@"
   rm -rf "$@"
 }
+
 
 # mostly_clean
 # ------------
@@ -1518,7 +1519,7 @@ input_file_name_decode ()
   # though the user may be able to reenter a valid filename at the tex
   # prompt (assuming they're attending the terminal), this script won't
   # be able to find the right xref files and so forth.
-  test  -r "$command_line_filename" ||
+  test -r "$command_line_filename" ||
     error 1 "cannot read $command_line_filename, skipping."
 
   # Get the name of the current directory.
